version: "3.8"
services:
  mongo:
    container_name: ${MONGO_HOSTNAME}
    image : mongo:latest
    volumes:
      # Database first time startup script
      - ./server/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      
      # Database volume
      - mongodb-data:/data/db
    networks:
      - mongodb_network
    #ports:
    #- ${MONGO_PORT}:27017
    restart: unless-stopped
    environment:
      # Username and password to access database
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

      # Variables for startup script
      - APP_USER=${APP_USER}
      - APP_PWD=${APP_PWD}
      - DB_COLLECTION_NAME=${DB_COLLECTION_NAME}

  crypto-server:
    container_name: crypto-server
    image : node-docker:latest
    depends_on:
      - mongo
    networks:
      - mongodb_network
    ports:
    - 3000:3000
    restart: unless-stopped
volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongodb_network:
    name: mongodb_network